#! /bin/bash

# get index of an empty window, if it exists
index=$(yabai -m query --spaces --display | jq -e '.[] | select( (.windows | length == 0) ) | .index' | tail -n 1)
# index=$(yabai -m query --spaces --display | jq -e '.[] | select( (.windows | length == 0) or (.["first-window"] == 0 and .["last-window"] == 0)) | .index' | tail -n 1)

# if an empty window is found, return it and exit
[[ ! -z $index ]] && echo $index && exit

# otherwise, crate a new window and return its index
yabai -m space --create && index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')"

echo $index
