#! /bin/bash

cmdline_window_id=$(\
  yabai -m query --windows | 
  jq 'map(select(.scratchpad == "cmdline")) | last' |
  jq '.id' 2> /dev/null
)

if [[ -z $cmdline_window_id || $cmdline_window_id == 'null' ]]; then
  yabai -m signal --add label=float_next_window_created event=window_created action='yabai -m signal --remove float_next_window_created; yabai -m signal --remove float_next_application_launched; yabai -m window $YABAI_WINDOW_ID --toggle float --grid 8:5:1:1:3:1 --scratchpad cmdline'; \
  yabai -m signal --add label=float_next_application_launched event=application_launched action='yabai -m signal --remove float_next_window_created; yabai -m signal --remove float_next_application_launched; yabai -m query --windows | jq -r ".[] | select(.pid == $YABAI_PROCESS_ID).id" | xargs -I{} yabai -m window {} --toggle float --grid 8:5:1:1:3:1 --scratchpad cmdline' ; \
  osascript ~/.config/skhd/wezterm.scpt
  exit 0
fi

yabai -m window $cmdline_window_id --toggle float
