#!/usr/bin/env bash

PLUGIN_DIR=${CONFIG_DIR}/plugins

source ${CONFIG_DIR}/colors/catppuccin-frappe.sh
source ${CONFIG_DIR}/icon_map.sh

sketchybar --bar position=top height=34 color=0xff"${COLOR_SURFACE0}"
sketchybar --add event aerospace_mode_change
sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_update_unfocused_window

default=(
  padding_left=4
  padding_right=4
  icon.font="FiraCode Nerd Font:Bold:17.0"
  label.font="JetBrainsMono Nerd Font:Bold:14.0"
  icon.color=${DEFAULT_TEXT_COLOR}
  label.color=${DEFAULT_TEXT_COLOR}
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  background.color="$DEFAULT_BACKGROUND_COLOR"
  background.border_width=1
  background.border_color=0xff"${COLOR_SURFACE0}"
  background.corner_radius=7
  background.height=25
  blur_radius=30
  background.drawing=off
)

sketchybar --default "${default[@]}"

sketchybar --add item logo left \
  --set logo icon="" \
  icon.font="Hack Nerd Font:Bold:20.0" \
  label.drawing=off \
  icon.padding_left=9 \
  icon.y_offset=1 \
  background.drawing=off \
  padding_left=-8

workspaces=$(printf "%s\n" $(aerospace list-workspaces --all) Mail Slack Calendar NSP | sort | uniq)
for sid in $(echo $workspaces); do
  space=left
  [[ ! $sid =~ [0-9] ]] && space=q
  sketchybar --add item space.$sid $space \
    --set space.$sid \
    icon.font="Hack Nerd Font:Bold:14.0" \
    label.font="sketchybar-app-font:Normal:12.0" \
    label.y_offset=-1 \
    background.drawing=off \
    background.height=25 \
    background.corner_radius=7 \
    icon="$sid" \
    click_script="aerospace workspace $sid" \
    drawing=off

done

# add icons for app-based workspaces
for sid in Mail Slack Calendar NSP; do
  __icon_map "$sid"
  icon_result=$icon_result
  sketchybar --set space.$sid icon="" icon.drawing=off label="$icon_result" label.y_offset=0 label.font="sketchybar-app-font:Normal:13.0"
done

# HACK: updating bar with events tied to hidden item
sketchybar --add item workspace-daemon left \
  --set workspace-daemon drawing=off \
  script=${CONFIG_DIR}/update-workspaces.sh \
  --subscribe workspace-daemon front_app_switched aerospace_workspace_change aerospace_update_unfocused_window

sketchybar --add item clock right --set clock \
  update_freq=10 \
  script=${PLUGIN_DIR}/"clock.sh" \
  padding_right=0 \
  label.font="Lucida Grande:Regular:14.0" \
  icon.drawing=off \
  label.y_offset=0 \
  padding_left=2

sketchybar --add item battery right --set battery \
  update_freq=150 \
  script=${PLUGIN_DIR}/"battery.sh" \
  icon.font="Lucida Grande:Regular:17.0" \
  icon.y_offset=0 \
  label.drawing=off \
  padding_left=8 padding_right=8 \
  --subscribe battery system_woke power_source_change

sketchybar --add item aerospace-mode q --set aerospace-mode \
  icon.drawing=off \
  label.drawing=off \
  background.drawing=off \
  background.corner_radius=7 \
  label.padding_left=8 \
  label.padding_right=8 \
  background.height=25 \
  script=${PLUGIN_DIR}/"aerospace_mode.sh" \
  --subscribe aerospace-mode aerospace_mode_change

sketchybar --update
