#!/usr/bin/env bash

PLUGIN_DIR=${CONFIG_DIR}/plugins

source ${CONFIG_DIR}/colors/catppuccin-frappe.sh

##### Bar Appearance #####

DEFAULT_BACKGROUND_COLOR=0xff"${COLOR_SURFACE2}"
DEFAULT_TEXT_COLOR=0xff"${COLOR_TEXT}"
DEFAULT_BORDER_COLOR=0xff"${COLOR_SURFACE0}"

HIGHLIGHT_BACKGROUND_COLOR=0xff"${COLOR_SURFACE2}"
HIGHLIGHT_TEXT_COLOR=0xCC"${COLOR_MAROON}"
HIGHLIGHT_BORDER_COLOR=0xCC"${COLOR_MAROON}"

sketchybar --bar position=top height=34 color=0xff"${COLOR_SURFACE0}"

##### Changing Defaults #####
default=(
  padding_left=4
  padding_right=4
  icon.font="FiraCode Nerd Font:Bold:17.0"
  label.font="FiraCode Nerd Font:Bold:14.0"
  icon.color=${DEFAULT_TEXT_COLOR}
  label.color=${DEFAULT_TEXT_COLOR}
  icon.padding_left=8
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=8
  background.color="$DEFAULT_BACKGROUND_COLOR"
  background.border_width=1
  background.border_color=0xff"${COLOR_SURFACE0}"
  background.corner_radius=20
  background.height=23
  blur_radius=30
)

sketchybar --default "${default[@]}"

##### Adding Apple Logo #####

# TODO: add aerospace mode indicator
sketchybar --add item logo left \
  --set logo icon="" \
  icon.font="Hack Nerd Font:Bold:23.0" \
  label.drawing=off \
  icon.padding_left=9 \
  icon.y_offset=1 \
  background.drawing=off \
  padding_left=-8

##### Adding Workspaces Indicators #####

workspaces=$(aerospace list-workspaces --all)
for sid in $(echo $workspaces); do

  sketchybar --add item space.$sid left \
    --set space.$sid \
    icon.font="Hack Nerd Font:Bold:14.0" \
    label.font="sketchybar-app-font:Normal:12.0" \
    label.y_offset=-1 \
    background.drawing=on \
    background.height=25 \
    background.corner_radius=7 \
    icon="$sid" \
    click_script="aerospace workspace $sid"

done

sketchybar --add item clock right \
  --set clock update_freq=10 icon= script=${PLUGIN_DIR}/"clock.sh" padding_right=-8 label.color=0xFF992B3F5 icon.font="Hack Nerd Font:Bold:15.0" label.font="Hack Nerd Font:Bold:15.0" \
  --add item battery right \
  --set battery label.font="Hack Nerd Font:Bold:15.0" update_freq=150 script=${PLUGIN_DIR}/"battery.sh" \
  icon.font="Hack Nerd Font:Regular:17.0" icon.y_offset=1 label.color=0xFF992B3F5 \
  --subscribe battery system_woke power_source_change

# sketchybar --add bracket spaces '/space\..*/'
#
# sketchybar --add item front_app.app e \
#   --set front_app.app \
#   icon.font="sketchybar-app-font:Normal:16.0" \
#   icon.color=0xFFFFB74D \
#   label.color=0xFFFFFFFF \
#   padding_right=0 \
#   label.max_chars=16 \
#   scroll_texts=on \
#   background.drawing=off \
#   script="${CONFIG_DIR}/front_app.sh" \
#   --subscribe front_app.app front_app_switched
#
# sketchybar --add item front_app.title e \
#   --set front_app.title \
#   label.font="Hack Nerd Font:Bold:12.0" \
#   label.color=0xFF992B3F5 \
#   label.max_chars=26 \
#   padding_left=0 \
#   scroll_texts=on \
#   icon.drawing=off \
#   background.drawing=off \
#   label = "Title" \
#   script="${CONFIG_DIR}/front_app_title.sh" \
#   --subscribe front_app.title front_app_switched
#
# sketchybar --add bracket front_app '/front_app.*/'

# sketchybar --add item clock right \
#   --set clock update_freq=10 icon= script="/nix/store/myzvvjkv1ybr4hm2864yn7b9vlv42k38-clock.sh" padding_right=-8 label.color=0xFF992B3F5 label.font="Hack Nerd Font:Bold:12.0" \
#   --add item volume right \
#   --set volume script="/nix/store/fx1lz7jvpbczpa2j0h9h4yxf6ag1wjqh-volume.sh" label.color=0xFF992B3F5 label.font="Hack Nerd Font:Bold:12.0" \
#   --subscribe volume volume_change \
#   --add item battery right \
#   --set battery label.font="Hack Nerd Font:Bold:12.0" update_freq=120 script="/nix/store/r3wwhcffp3fca6firwqs75ia64nmg0pz-battery.sh" \
#   icon.font="SF Pro:Regular:17.0" icon.y_offset=1 label.color=0xFF992B3F5 \
#   --subscribe battery system_woke power_source_change

sketchybar --hotload
sketchybar --update
